spring.application.name=PrepaidSolution

#mqtt.broker.uri=tcp://5.196.78.28:1883
mqtt.broker.uri=mqtt://5.196.78.28:1883
mqtt.broker.serverHost=5.196.78.28
mqtt.broker.serverPort=1883
mqtt.topic=modbus/data
#mqtt.topic=outTopic/#

# RabbitMQ connection settings
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


#spring.datasource.url= jdbc:mysql://localhost:3306/prepaid_solution
#spring.datasource.username= root
#spring.datasource.password= root

spring.datasource.url= jdbc:mysql://100.124.131.81:3306/prepaid_solution
spring.datasource.username= akash
spring.datasource.password= root


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akashyadav.8498@gmail.com
spring.mail.password=hwmsjjclrstgzsoy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
