spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prepaid_solution
    username: app_user
    password: ME@@ppu$er8498

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080