spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://localhost:3306/prepaid_solution
    username: root
    password: root

#server:
#  servlet:
#    session:
#      timeout: 30d
#      cookie:
#        max-age: 2592000   # 30 days
#        http-only: true
#        same-site: lax

server:
  servlet:
    session:
      timeout: 1m
      cookie:
        max-age: 60
        http-only: true
        same-site: lax

